### PR TITLE
ManualClient: Add support for one-click client configuration files

### PR DESCRIPTION
**Pull request by silasary**
This was basically lifted from the Minecraft implementation.

Will require APWorlds to update their python files to take advantage of it.

### CODE REVIEW

**Comment by FuzzyGamesOn** [comment]
Looks great! Will plan to merge this in and add to the next unstable template release, planned for this weekend. 😃 Thanks for contributing to Manual!

**Comment by FuzzyGamesOn** [comment]
Going to get the next stable apworld template out with the init changes here, then a client update for the other half sometime this week. (Then merging.)

**Comment by silasary** [comment]
I'm considering updating the output to also include locations and items, so that we can avoid needing the APWorld in the client.

**Comment by FuzzyGamesOn** [comment]
Gonna go ahead and merge this as-is. Just PR the items/locations thing as a separate thing if you end up doing it, same branch is fine. 😃

**Pull request merged**
